export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
  supportsSkinTone?: boolean;
}

export interface EmojiCategory {
  id: string;
  name: string;
  emojis: EmojiItem[];
}

export const SKIN_TONES = [
  { id: 'default', label: 'Default Yellow', modifier: '', symbol: '✋' },
  { id: 'light', label: 'Light', modifier: '\u{1F3FB}', symbol: '✋🏻' },
  { id: 'medium-light', label: 'Medium-Light', modifier: '\u{1F3FC}', symbol: '✋🏼' },
  { id: 'medium', label: 'Medium', modifier: '\u{1F3FD}', symbol: '✋🏽' },
  { id: 'medium-dark', label: 'Medium-Dark', modifier: '\u{1F3FE}', symbol: '✋🏾' },
  { id: 'dark', label: 'Dark', modifier: '\u{1F3FF}', symbol: '✋🏿' },
] as const;

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & emotion',
    emojis: [
      { emoji: '😀', name: 'Grinning Face', keywords: ['smile', 'happy', 'face'] },
      { emoji: '😃', name: 'Grinning Face with Big Eyes', keywords: ['happy', 'joy', 'smile'] },
      { emoji: '😄', name: 'Grinning Face with Smiling Eyes', keywords: ['happy', 'joy', 'laugh'] },
      { emoji: '😁', name: 'Beaming Face with Smiling Eyes', keywords: ['smile', 'teeth', 'happy'] },
      { emoji: '😆', name: 'Grinning Squinting Face', keywords: ['laugh', 'happy', 'haha'] },
      { emoji: '😅', name: 'Grinning Face with Sweat', keywords: ['sweat', 'relief', 'nervous'] },
      { emoji: '🤣', name: 'Rolling on the Floor Laughing', keywords: ['rofl', 'lol', 'laugh'] },
      { emoji: '😂', name: 'Face with Tears of Joy', keywords: ['tears', 'crying', 'laugh', 'lol'] },
      { emoji: '🙂', name: 'Slightly Smiling Face', keywords: ['smile', 'pleasant', 'mild'] },
      { emoji: '🙃', name: 'Upside-Down Face', keywords: ['silly', 'sarcasm', 'irony'] },
      { emoji: '🫠', name: 'Melting Face', keywords: ['melt', 'hot', 'liquid', 'disappear'] },
      { emoji: '😉', name: 'Winking Face', keywords: ['wink', 'flirt', 'playful'] },
      { emoji: '😊', name: 'Smiling Face with Smiling Eyes', keywords: ['blush', 'warm', 'happy'] },
      { emoji: '😇', name: 'Smiling Face with Halo', keywords: ['angel', 'innocent', 'good'] },
      { emoji: '🥰', name: 'Smiling Face with Hearts', keywords: ['love', 'crush', 'adore'] },
      { emoji: '😍', name: 'Heart Eyes', keywords: ['love', 'infatuation', 'heart'] },
      { emoji: '🤩', name: 'Star-Struck', keywords: ['star', 'eyes', 'excited', 'wow'] },
      { emoji: '😘', name: 'Face Blowing a Kiss', keywords: ['kiss', 'love', 'affection'] },
      { emoji: '😗', name: 'Kissing Face', keywords: ['kiss', 'whistle'] },
      { emoji: '😚', name: 'Kissing Face with Closed Eyes', keywords: ['kiss', 'affection'] },
      { emoji: '😙', name: 'Kissing Face with Smiling Eyes', keywords: ['kiss', 'happy'] },
      { emoji: '😋', name: 'Face Savoring Food', keywords: ['yum', 'delicious', 'tongue'] },
      { emoji: '😛', name: 'Face with Tongue', keywords: ['tongue', 'playful', 'silly'] },
      { emoji: '😜', name: 'Winking Face with Tongue', keywords: ['wink', 'crazy', 'party'] },
      { emoji: '🤪', name: 'Zany Face', keywords: ['wild', 'crazy', 'goofy'] },
      { emoji: '😝', name: 'Squinting Face with Tongue', keywords: ['tongue', 'playful'] },
      { emoji: '🤑', name: 'Money-Mouth Face', keywords: ['money', 'rich', 'dollar', 'cash'] },
      { emoji: '🤗', name: 'Smiling Face with Open Hands', keywords: ['hug', 'open', 'embrace'] },
      { emoji: '🫣', name: 'Face with Peeking Eye', keywords: ['peek', 'shy', 'scared', 'hide'] },
      { emoji: '🤫', name: 'Shushing Face', keywords: ['quiet', 'secret', 'hush', 'shh'] },
      { emoji: '🤔', name: 'Thinking Face', keywords: ['think', 'ponder', 'wonder', 'hmm'] },
      { emoji: '🫡', name: 'Saluting Face', keywords: ['salute', 'respect', 'yes', 'ok'] },
      { emoji: '🤐', name: 'Zipper-Mouth Face', keywords: ['secret', 'silent', 'zip'] },
      { emoji: '🤨', name: 'Face with Raised Eyebrow', keywords: ['skeptic', 'doubt', 'suspicious'] },
      { emoji: '😐', name: 'Neutral Face', keywords: ['neutral', 'meh', 'straight'] },
      { emoji: '😑', name: 'Expressionless Face', keywords: ['deadpan', 'unimpressed'] },
      { emoji: '😶', name: 'Face Without Mouth', keywords: ['quiet', 'mute', 'blank'] },
      { emoji: '🫥', name: 'Dotted Line Face', keywords: ['invisible', 'disappear', 'introvert'] },
      { emoji: '😏', name: 'Smirking Face', keywords: ['smirk', 'smug', 'flirt'] },
      { emoji: '😒', name: 'Unamused Face', keywords: ['bored', 'annoyed', 'displeased'] },
      { emoji: '🙄', name: 'Face with Rolling Eyes', keywords: ['eyeroll', 'whatever', 'annoyed'] },
      { emoji: '😬', name: 'Grimacing Face', keywords: ['awkward', 'nervous', 'yikes'] },
      { emoji: '😮‍💨', name: 'Face Exhaling', keywords: ['sigh', 'relief', 'tired', 'exhale'] },
      { emoji: '🤥', name: 'Lying Face', keywords: ['pinocchio', 'lie', 'nose'] },
      { emoji: '😌', name: 'Relieved Face', keywords: ['peaceful', 'calm', 'serene'] },
      { emoji: '😔', name: 'Pensive Face', keywords: ['sad', 'depressed', 'thoughtful'] },
      { emoji: '😪', name: 'Sleepy Face', keywords: ['tired', 'sleep', 'rest'] },
      { emoji: '🤤', name: 'Drooling Face', keywords: ['drool', 'craving', 'hungry'] },
      { emoji: '😴', name: 'Sleeping Face', keywords: ['sleep', 'zzz', 'night'] },
      { emoji: '😷', name: 'Face with Medical Mask', keywords: ['mask', 'sick', 'covid', 'health'] },
      { emoji: '🤒', name: 'Face with Thermometer', keywords: ['fever', 'sick', 'ill'] },
      { emoji: '🤕', name: 'Face with Head-Bandage', keywords: ['hurt', 'bandage', 'injury'] },
      { emoji: '🤢', name: 'Nauseated Face', keywords: ['sick', 'gross', 'green'] },
      { emoji: '🤮', name: 'Face Vomiting', keywords: ['throw up', 'gross', 'puke'] },
      { emoji: '🤧', name: 'Sneezing Face', keywords: ['sneeze', 'cold', 'tissue'] },
      { emoji: '🥵', name: 'Hot Face', keywords: ['heat', 'summer', 'sweat', 'warm'] },
      { emoji: '🥶', name: 'Cold Face', keywords: ['freeze', 'ice', 'winter', 'chill'] },
      { emoji: '🥴', name: 'Woozy Face', keywords: ['dizzy', 'drunk', 'tired'] },
      { emoji: '😵', name: 'Face with Crossed-Out Eyes', keywords: ['dead', 'dizzy', 'knockout'] },
      { emoji: '😵‍💫', name: 'Face with Spiral Eyes', keywords: ['hypnotized', 'dizzy', 'overwhelmed'] },
      { emoji: '🤯', name: 'Exploding Head', keywords: ['mind blown', 'shock', 'brain'] },
      { emoji: '🤠', name: 'Cowboy Hat Face', keywords: ['western', 'country', 'adventure'] },
      { emoji: '🥳', name: 'Partying Face', keywords: ['celebrate', 'party', 'birthday', 'horn'] },
      { emoji: '🥸', name: 'Disguised Face', keywords: ['glasses', 'mustache', 'spy', 'incognito'] },
      { emoji: '😎', name: 'Smiling Face with Sunglasses', keywords: ['cool', 'sun', 'swag'] },
      { emoji: '🤓', name: 'Nerd Face', keywords: ['geek', 'glasses', 'study', 'smart'] },
      { emoji: '🧐', name: 'Face with Monocle', keywords: ['curious', 'examine', 'inspect'] },
      { emoji: '😕', name: 'Confused Face', keywords: ['puzzled', 'unsure'] },
      { emoji: '🫤', name: 'Face with Diagonal Mouth', keywords: ['meh', 'skeptical', 'confused'] },
      { emoji: '😟', name: 'Worried Face', keywords: ['concern', 'nervous'] },
      { emoji: '🙁', name: 'Slightly Frowning Face', keywords: ['sad', 'disappointed'] },
      { emoji: '😮', name: 'Face with Open Mouth', keywords: ['surprise', 'wow', 'gasp'] },
      { emoji: '😯', name: 'Hushed Face', keywords: ['stunned', 'speechless'] },
      { emoji: '😲', name: 'Astonished Face', keywords: ['shock', 'amazed'] },
      { emoji: '😳', name: 'Flushed Face', keywords: ['blush', 'embarrassed', 'wide eyes'] },
      { emoji: '🥺', name: 'Pleading Face', keywords: ['puppy eyes', 'begging', 'cute', 'please'] },
      { emoji: '🥹', name: 'Face Holding Back Tears', keywords: ['emotional', 'gratitude', 'proud'] },
      { emoji: '😦', name: 'Frowning Face with Open Mouth', keywords: ['scared', 'shock'] },
      { emoji: '😧', name: 'Anguished Face', keywords: ['pain', 'hurt'] },
      { emoji: '😨', name: 'Fearful Face', keywords: ['fear', 'scared'] },
      { emoji: '😰', name: 'Anxious Face with Sweat', keywords: ['nervous', 'scared', 'stress'] },
      { emoji: '😥', name: 'Sad but Relieved Face', keywords: ['whew', 'relief', 'almost'] },
      { emoji: '😢', name: 'Crying Face', keywords: ['tear', 'sad', 'heartbroken'] },
      { emoji: '😭', name: 'Loudly Crying Face', keywords: ['sob', 'tears', 'crying', 'sad'] },
      { emoji: '😱', name: 'Face Screaming in Fear', keywords: ['scream', 'munch', 'scared', 'horror'] },
      { emoji: '😖', name: 'Confounded Face', keywords: ['frustrated', 'quiver'] },
      { emoji: '😣', name: 'Persevering Face', keywords: ['struggle', 'endure'] },
      { emoji: '😞', name: 'Disappointed Face', keywords: ['sad', 'let down'] },
      { emoji: '😓', name: 'Downcast Face with Sweat', keywords: ['sweat', 'tired', 'exhausted'] },
      { emoji: '😩', name: 'Weary Face', keywords: ['tired', 'whining', 'overwhelmed'] },
      { emoji: '😫', name: 'Tired Face', keywords: ['exhausted', 'done'] },
      { emoji: '🥱', name: 'Yawning Face', keywords: ['sleepy', 'bored', 'yawn'] },
      { emoji: '😤', name: 'Face with Steam From Nose', keywords: ['triumph', 'pride', 'determined'] },
      { emoji: '😡', name: 'Enraged Face', keywords: ['angry', 'mad', 'red'] },
      { emoji: '😠', name: 'Angry Face', keywords: ['mad', 'annoyed'] },
      { emoji: '🤬', name: 'Face with Symbols on Mouth', keywords: ['swear', 'curse', 'angry'] },
      { emoji: '😈', name: 'Smiling Face with Horns', keywords: ['devil', 'mischief', 'evil'] },
      { emoji: '👿', name: 'Angry Face with Horns', keywords: ['demon', 'devil', 'mad'] },
      { emoji: '💀', name: 'Skull', keywords: ['dead', 'skeleton', 'died', 'danger'] },
      { emoji: '☠️', name: 'Skull and Crossbones', keywords: ['pirate', 'toxic', 'danger'] },
      { emoji: '💩', name: 'Pile of Poo', keywords: ['poop', 'funny', 'turd'] },
      { emoji: '🤡', name: 'Clown Face', keywords: ['circus', 'fool', 'joke'] },
      { emoji: '👹', name: 'Ogre', keywords: ['monster', 'japan', 'mask'] },
      { emoji: '👺', name: 'Goblin', keywords: ['japanese', 'tengu'] },
      { emoji: '👻', name: 'Ghost', keywords: ['halloween', 'spooky', 'boo'] },
      { emoji: '👽', name: 'Alien', keywords: ['extraterrestrial', 'ufo', 'space'] },
      { emoji: '👾', name: 'Alien Monster', keywords: ['retro', 'game', 'arcade', 'pixel'] },
      { emoji: '🤖', name: 'Robot', keywords: ['bot', 'ai', 'tech', 'automation', 'machine'] },
    ],
  },
  {
    id: 'people',
    name: 'People & body',
    emojis: [
      { emoji: '👋', name: 'Waving Hand', keywords: ['wave', 'hello', 'bye'], supportsSkinTone: true },
      { emoji: '🤚', name: 'Raised Back of Hand', keywords: ['backhand', 'raised'], supportsSkinTone: true },
      { emoji: '🖐️', name: 'Hand with Fingers Splayed', keywords: ['hand', 'five'], supportsSkinTone: true },
      { emoji: '✋', name: 'Raised Hand', keywords: ['stop', 'high five', 'palm'], supportsSkinTone: true },
      { emoji: '🖖', name: 'Vulcan Salute', keywords: ['star trek', 'spock', 'live long'], supportsSkinTone: true },
      { emoji: '👌', name: 'OK Hand', keywords: ['perfect', 'good', 'agree'], supportsSkinTone: true },
      { emoji: '🤌', name: 'Pinched Fingers', keywords: ['italian', 'gesture', 'what'], supportsSkinTone: true },
      { emoji: '🤏', name: 'Pinching Hand', keywords: ['small', 'little', 'tiny'], supportsSkinTone: true },
      { emoji: '✌️', name: 'Victory Hand', keywords: ['peace', 'victory', 'two'], supportsSkinTone: true },
      { emoji: '🤞', name: 'Crossed Fingers', keywords: ['luck', 'hope', 'wish'], supportsSkinTone: true },
      { emoji: '🫰', name: 'Hand with Index Finger and Thumb Crossed', keywords: ['kpop', 'heart', 'money'], supportsSkinTone: true },
      { emoji: '🤟', name: 'Love-You Gesture', keywords: ['love', 'sign'], supportsSkinTone: true },
      { emoji: '🤘', name: 'Sign of the Horns', keywords: ['rock', 'metal', 'cool'], supportsSkinTone: true },
      { emoji: '🤙', name: 'Call Me Hand', keywords: ['shaka', 'phone', 'surf'], supportsSkinTone: true },
      { emoji: '👈', name: 'Backhand Index Pointing Left', keywords: ['point', 'left'], supportsSkinTone: true },
      { emoji: '👉', name: 'Backhand Index Pointing Right', keywords: ['point', 'right'], supportsSkinTone: true },
      { emoji: '👆', name: 'Backhand Index Pointing Up', keywords: ['point', 'up'], supportsSkinTone: true },
      { emoji: '🖕', name: 'Middle Finger', keywords: ['rude'], supportsSkinTone: true },
      { emoji: '👇', name: 'Backhand Index Pointing Down', keywords: ['point', 'down'], supportsSkinTone: true },
      { emoji: '☝️', name: 'Index Pointing Up', keywords: ['first', 'listen', 'up'], supportsSkinTone: true },
      { emoji: '👍', name: 'Thumbs Up', keywords: ['like', 'approve', 'agree', 'yes'], supportsSkinTone: true },
      { emoji: '👎', name: 'Thumbs Down', keywords: ['dislike', 'no', 'reject'], supportsSkinTone: true },
      { emoji: '✊', name: 'Raised Fist', keywords: ['power', 'strength'], supportsSkinTone: true },
      { emoji: '👊', name: 'Oncoming Fist', keywords: ['fist bump', 'punch'], supportsSkinTone: true },
      { emoji: '🤛', name: 'Left-Facing Fist', keywords: ['bump', 'left'], supportsSkinTone: true },
      { emoji: '🤜', name: 'Right-Facing Fist', keywords: ['bump', 'right'], supportsSkinTone: true },
      { emoji: '👏', name: 'Clapping Hands', keywords: ['applause', 'praise', 'bravo'], supportsSkinTone: true },
      { emoji: '🙌', name: 'Raising Hands', keywords: ['hooray', 'celebrate', 'praise'], supportsSkinTone: true },
      { emoji: '🫶', name: 'Heart Hands', keywords: ['love', 'care', 'heart'], supportsSkinTone: true },
      { emoji: '👐', name: 'Open Hands', keywords: ['welcome', 'open'], supportsSkinTone: true },
      { emoji: '🤲', name: 'Palms Up Together', keywords: ['prayer', 'cupped'], supportsSkinTone: true },
      { emoji: '🤝', name: 'Handshake', keywords: ['deal', 'agreement', 'partner'], supportsSkinTone: false },
      { emoji: '🙏', name: 'Folded Hands', keywords: ['pray', 'thank you', 'please', 'hope'], supportsSkinTone: true },
      { emoji: '✍️', name: 'Writing Hand', keywords: ['write', 'author', 'pen'], supportsSkinTone: true },
      { emoji: '💅', name: 'Nail Polish', keywords: ['manicure', 'care', 'sass'], supportsSkinTone: true },
      { emoji: '🤳', name: 'Selfie', keywords: ['camera', 'phone', 'self'], supportsSkinTone: true },
      { emoji: '💪', name: 'Flexed Biceps', keywords: ['muscle', 'strong', 'power', 'gym'], supportsSkinTone: true },
      { emoji: '🧠', name: 'Brain', keywords: ['smart', 'intellect', 'think', 'mind'] },
      { emoji: '🫀', name: 'Anatomical Heart', keywords: ['organ', 'cardio', 'pulse'] },
      { emoji: '🫁', name: 'Lungs', keywords: ['breathe', 'respiration'] },
      { emoji: '👀', name: 'Eyes', keywords: ['look', 'see', 'watch'] },
      { emoji: '👁️', name: 'Eye', keywords: ['vision', 'look'] },
      { emoji: '🧑‍💻', name: 'Technologist', keywords: ['developer', 'coder', 'engineer', 'programmer'] },
      { emoji: '🧑‍🔬', name: 'Scientist', keywords: ['researcher', 'lab', 'biology', 'chemistry'] },
      { emoji: '🧑‍🎨', name: 'Artist', keywords: ['creative', 'painter', 'design'] },
      { emoji: '🧑‍🚀', name: 'Astronaut', keywords: ['space', 'rocket', 'cosmos'] },
    ],
  },
  {
    id: 'nature',
    name: 'Animals & nature',
    emojis: [
      { emoji: '🐶', name: 'Dog Face', keywords: ['puppy', 'pet', 'animal'] },
      { emoji: '🐱', name: 'Cat Face', keywords: ['kitten', 'pet', 'meow'] },
      { emoji: '🐭', name: 'Mouse Face', keywords: ['rodent', 'small'] },
      { emoji: '🐹', name: 'Hamster Face', keywords: ['pet', 'cute'] },
      { emoji: '🐰', name: 'Rabbit Face', keywords: ['bunny', 'easter'] },
      { emoji: '🦊', name: 'Fox Face', keywords: ['clever', 'wild'] },
      { emoji: '🐻', name: 'Bear Face', keywords: ['grizzly', 'brown'] },
      { emoji: '🐼', name: 'Panda Face', keywords: ['bamboo', 'bear', 'cute'] },
      { emoji: '🐨', name: 'Koala', keywords: ['australia', 'cute'] },
      { emoji: '🐯', name: 'Tiger Face', keywords: ['fierce', 'cat', 'wild'] },
      { emoji: '🦁', name: 'Lion Face', keywords: ['king', 'brave', 'mane'] },
      { emoji: '🐮', name: 'Cow Face', keywords: ['milk', 'farm'] },
      { emoji: '🐷', name: 'Pig Face', keywords: ['oink', 'farm'] },
      { emoji: '🐸', name: 'Frog Face', keywords: ['amphibian', 'pond'] },
      { emoji: '🐵', name: 'Monkey Face', keywords: ['jungle', 'curious'] },
      { emoji: '🐔', name: 'Chicken', keywords: ['bird', 'poultry', 'farm'] },
      { emoji: '🐧', name: 'Penguin', keywords: ['antarctic', 'bird', 'linux'] },
      { emoji: '🐦', name: 'Bird', keywords: ['fly', 'nature'] },
      { emoji: '🐤', name: 'Baby Chick', keywords: ['yellow', 'cute'] },
      { emoji: '🦅', name: 'Eagle', keywords: ['bird', 'freedom', 'sharp'] },
      { emoji: '🦉', name: 'Owl', keywords: ['wise', 'night', 'knowledge'] },
      { emoji: '🦇', name: 'Bat', keywords: ['vampire', 'cave'] },
      { emoji: '🐺', name: 'Wolf', keywords: ['pack', 'wild', 'howl'] },
      { emoji: '🦄', name: 'Unicorn', keywords: ['magic', 'fantasy', 'startup'] },
      { emoji: '🐝', name: 'Honeybee', keywords: ['busy', 'honey', 'pollen'] },
      { emoji: '🐛', name: 'Bug', keywords: ['insect', 'caterpillar', 'debug'] },
      { emoji: '🦋', name: 'Butterfly', keywords: ['beauty', 'wings', 'transform'] },
      { emoji: '🐌', name: 'Snail', keywords: ['slow', 'shell'] },
      { emoji: '🐞', name: 'Lady Beetle', keywords: ['ladybug', 'luck'] },
      { emoji: '🐙', name: 'Octopus', keywords: ['ocean', 'tentacles', 'smart'] },
      { emoji: '🐬', name: 'Dolphin', keywords: ['ocean', 'clever', 'swim'] },
      { emoji: '🐳', name: 'Spouting Whale', keywords: ['docker', 'sea', 'mammal'] },
      { emoji: '🦈', name: 'Shark', keywords: ['ocean', 'predator'] },
      { emoji: '🪴', name: 'Potted Plant', keywords: ['plant', 'garden', 'indoor', 'green'] },
      { emoji: '🌲', name: 'Evergreen Tree', keywords: ['pine', 'nature', 'forest'] },
      { emoji: '🌳', name: 'Deciduous Tree', keywords: ['nature', 'wood', 'green'] },
      { emoji: '🌴', name: 'Palm Tree', keywords: ['tropical', 'beach', 'summer'] },
      { emoji: '🌵', name: 'Cactus', keywords: ['desert', 'spikes'] },
      { emoji: '🌾', name: 'Sheaf of Rice', keywords: ['crop', 'grain'] },
      { emoji: '🌿', name: 'Herb', keywords: ['leaf', 'medicinal', 'natural'] },
      { emoji: '☘️', name: 'Shamrock', keywords: ['ireland', 'green'] },
      { emoji: '🍀', name: 'Four Leaf Clover', keywords: ['lucky', 'fortune'] },
      { emoji: '🍁', name: 'Maple Leaf', keywords: ['autumn', 'canada', 'fall'] },
      { emoji: '🍂', name: 'Fallen Leaf', keywords: ['autumn', 'season'] },
      { emoji: '🍃', name: 'Leaf Fluttering in Wind', keywords: ['breeze', 'fresh'] },
      { emoji: '🍄', name: 'Mushroom', keywords: ['fungus', 'mario'] },
      { emoji: '🔥', name: 'Fire', keywords: ['hot', 'flame', 'lit', 'trending'] },
      { emoji: '⭐', name: 'Star', keywords: ['favorite', 'bright', 'gold', 'rating'] },
      { emoji: '🌟', name: 'Glowing Star', keywords: ['sparkle', 'shine'] },
      { emoji: '✨', name: 'Sparkles', keywords: ['clean', 'magic', 'ai', 'shine'] },
      { emoji: '⚡', name: 'High Voltage', keywords: ['lightning', 'fast', 'power', 'zap', 'energy'] },
    ],
  },
  {
    id: 'food',
    name: 'Food & drink',
    emojis: [
      { emoji: '🍏', name: 'Green Apple', keywords: ['fruit', 'healthy'] },
      { emoji: '🍎', name: 'Red Apple', keywords: ['fruit', 'teacher'] },
      { emoji: '🍐', name: 'Pear', keywords: ['fruit'] },
      { emoji: '🍊', name: 'Tangerine', keywords: ['orange', 'citrus'] },
      { emoji: '🍋', name: 'Lemon', keywords: ['citrus', 'sour'] },
      { emoji: '🍌', name: 'Banana', keywords: ['fruit', 'potassium'] },
      { emoji: '🍉', name: 'Watermelon', keywords: ['summer', 'sweet'] },
      { emoji: '🍇', name: 'Grapes', keywords: ['wine', 'fruit'] },
      { emoji: '🍓', name: 'Strawberry', keywords: ['berry', 'red'] },
      { emoji: '🫐', name: 'Blueberries', keywords: ['berry', 'fruit'] },
      { emoji: '🍒', name: 'Cherries', keywords: ['fruit', 'red'] },
      { emoji: '🍑', name: 'Peach', keywords: ['fruit', 'sweet'] },
      { emoji: '🥑', name: 'Avocado', keywords: ['guacamole', 'healthy'] },
      { emoji: '🍔', name: 'Hamburger', keywords: ['burger', 'fast food'] },
      { emoji: '🍟', name: 'French Fries', keywords: ['fast food', 'potatoes'] },
      { emoji: '🍕', name: 'Pizza', keywords: ['cheese', 'slice', 'italian'] },
      { emoji: '🥪', name: 'Sandwich', keywords: ['lunch', 'bread'] },
      { emoji: '🌮', name: 'Taco', keywords: ['mexican', 'food'] },
      { emoji: '🍣', name: 'Sushi', keywords: ['japanese', 'fish', 'rice'] },
      { emoji: '🍜', name: 'Steaming Bowl', keywords: ['ramen', 'noodles', 'soup'] },
      { emoji: '☕', name: 'Hot Beverage', keywords: ['coffee', 'tea', 'caffeine', 'espresso'] },
      { emoji: '🍵', name: 'Teacup Without Handle', keywords: ['matcha', 'green tea'] },
      { emoji: '🧋', name: 'Bubble Tea', keywords: ['boba', 'milk tea'] },
      { emoji: '🍺', name: 'Beer Mug', keywords: ['alcohol', 'drink', 'cheers'] },
      { emoji: '🍷', name: 'Wine Glass', keywords: ['red wine', 'drink'] },
    ],
  },
  {
    id: 'activity',
    name: 'Activities & sports',
    emojis: [
      { emoji: '⚽', name: 'Soccer Ball', keywords: ['football', 'sport'] },
      { emoji: '🏀', name: 'Basketball', keywords: ['hoop', 'nba', 'sport'] },
      { emoji: '🏈', name: 'American Football', keywords: ['superbowl', 'nfl'] },
      { emoji: '⚾', name: 'Baseball', keywords: ['mlb', 'ball'] },
      { emoji: '🎾', name: 'Tennis', keywords: ['racket', 'court'] },
      { emoji: '🎯', name: 'Bullseye', keywords: ['target', 'goal', 'hit', 'focus'] },
      { emoji: '🎮', name: 'Video Game', keywords: ['gaming', 'playstation', 'controller'] },
      { emoji: '🕹️', name: 'Joystick', keywords: ['arcade', 'game'] },
      { emoji: '🎲', name: 'Game Die', keywords: ['dice', 'random', 'chance'] },
      { emoji: '🧩', name: 'Puzzle Piece', keywords: ['jigsaw', 'problem', 'solve'] },
      { emoji: '♟️', name: 'Chess Pawn', keywords: ['strategy', 'game'] },
      { emoji: '🎨', name: 'Artist Palette', keywords: ['art', 'design', 'paint', 'colors'] },
      { emoji: '🏆', name: 'Trophy', keywords: ['winner', 'first', 'award', 'champion'] },
      { emoji: '🥇', name: '1st Place Medal', keywords: ['gold', 'first', 'champion'] },
      { emoji: '🥈', name: '2nd Place Medal', keywords: ['silver', 'runner up'] },
      { emoji: '🥉', name: '3rd Place Medal', keywords: ['bronze', 'third'] },
      { emoji: '🎖️', name: 'Military Medal', keywords: ['honor', 'veteran'] },
    ],
  },
  {
    id: 'travel',
    name: 'Travel & places',
    emojis: [
      { emoji: '🚗', name: 'Automobile', keywords: ['car', 'drive'] },
      { emoji: '🚕', name: 'Taxi', keywords: ['cab', 'uber'] },
      { emoji: '🚌', name: 'Bus', keywords: ['transit'] },
      { emoji: '🏎️', name: 'Racing Car', keywords: ['f1', 'speed'] },
      { emoji: '🚲', name: 'Bicycle', keywords: ['bike', 'cycling'] },
      { emoji: '🚀', name: 'Rocket', keywords: ['launch', 'space', 'startup', 'speed', 'fast'] },
      { emoji: '🛸', name: 'Flying Saucer', keywords: ['ufo', 'alien'] },
      { emoji: '✈️', name: 'Airplane', keywords: ['flight', 'travel', 'vacation'] },
      { emoji: '🛰️', name: 'Satellite', keywords: ['orbit', 'space', 'telecom'] },
      { emoji: '🚢', name: 'Ship', keywords: ['cruise', 'boat', 'ocean'] },
      { emoji: '⚓', name: 'Anchor', keywords: ['nautical', 'harbor'] },
      { emoji: '🗺️', name: 'World Map', keywords: ['geography', 'travel', 'plan'] },
      { emoji: '🏖️', name: 'Beach with Umbrella', keywords: ['vacation', 'summer'] },
      { emoji: '⛰️', name: 'Mountain', keywords: ['hike', 'climb', 'peak'] },
      { emoji: '🏔️', name: 'Snow-Capped Mountain', keywords: ['everest', 'winter'] },
      { emoji: '🏕️', name: 'Camping', keywords: ['tent', 'outdoors'] },
      { emoji: '🏢', name: 'Office Building', keywords: ['work', 'company', 'corp'] },
      { emoji: '🏠', name: 'House', keywords: ['home', 'residence'] },
      { emoji: '🏰', name: 'Castle', keywords: ['fairytale', 'royal'] },
    ],
  },
  {
    id: 'objects',
    name: 'Objects & tech',
    emojis: [
      { emoji: '💻', name: 'Laptop', keywords: ['computer', 'pc', 'mac', 'code', 'work', 'tech'] },
      { emoji: '🖥️', name: 'Desktop Computer', keywords: ['screen', 'monitor', 'pc'] },
      { emoji: '⌨️', name: 'Keyboard', keywords: ['typing', 'hardware'] },
      { emoji: '🖱️', name: 'Computer Mouse', keywords: ['click', 'hardware'] },
      { emoji: '🖨️', name: 'Printer', keywords: ['paper', 'office'] },
      { emoji: '💾', name: 'Floppy Disk', keywords: ['save', 'retro', 'storage'] },
      { emoji: '📱', name: 'Mobile Phone', keywords: ['iphone', 'android', 'cell'] },
      { emoji: '☎️', name: 'Telephone', keywords: ['call', 'ring'] },
      { emoji: '💡', name: 'Light Bulb', keywords: ['idea', 'insight', 'smart', 'bright'] },
      { emoji: '🔦', name: 'Flashlight', keywords: ['light', 'torch'] },
      { emoji: '📚', name: 'Books', keywords: ['reading', 'library', 'study', 'learn'] },
      { emoji: '📖', name: 'Open Book', keywords: ['read', 'documentation', 'manual'] },
      { emoji: '🔬', name: 'Microscope', keywords: ['science', 'research', 'lab', 'biology'] },
      { emoji: '🔭', name: 'Telescope', keywords: ['astronomy', 'stars', 'space'] },
      { emoji: '🧪', name: 'Test Tube', keywords: ['chemistry', 'experiment', 'lab'] },
      { emoji: '🧬', name: 'DNA', keywords: ['genetics', 'science', 'biology'] },
      { emoji: '📊', name: 'Bar Chart', keywords: ['analytics', 'metrics', 'stats', 'graph'] },
      { emoji: '📈', name: 'Chart Increasing', keywords: ['growth', 'profit', 'up'] },
      { emoji: '📉', name: 'Chart Decreasing', keywords: ['loss', 'down'] },
      { emoji: '📝', name: 'Memo', keywords: ['note', 'document', 'write', 'todo'] },
      { emoji: '📁', name: 'File Folder', keywords: ['directory', 'files', 'storage'] },
      { emoji: '📂', name: 'Open File Folder', keywords: ['directory', 'files'] },
      { emoji: '📅', name: 'Calendar', keywords: ['date', 'schedule', 'event'] },
      { emoji: '🗓️', name: 'Spiral Calendar', keywords: ['planner', 'date'] },
      { emoji: '📋', name: 'Clipboard', keywords: ['tasks', 'survey', 'checklist'] },
      { emoji: '📌', name: 'Pushpin', keywords: ['pin', 'note', 'board'] },
      { emoji: '📍', name: 'Round Pushpin', keywords: ['location', 'map'] },
      { emoji: '📎', name: 'Paperclip', keywords: ['attachment', 'link'] },
      { emoji: '🔗', name: 'Link', keywords: ['url', 'hyperlink', 'connection'] },
      { emoji: '🔒', name: 'Locked', keywords: ['secure', 'privacy', 'password'] },
      { emoji: '🔓', name: 'Unlocked', keywords: ['open', 'insecure'] },
      { emoji: '🔑', name: 'Key', keywords: ['access', 'password', 'login'] },
      { emoji: '🛡️', name: 'Shield', keywords: ['security', 'protect', 'safe', 'defense'] },
      { emoji: '⚙️', name: 'Gear', keywords: ['settings', 'config', 'preferences'] },
      { emoji: '🛠️', name: 'Hammer and Wrench', keywords: ['tools', 'build', 'dev'] },
      { emoji: '📦', name: 'Package', keywords: ['box', 'delivery', 'npm', 'module'] },
      { emoji: '💎', name: 'Gem Stone', keywords: ['diamond', 'valuable', 'ruby'] },
      { emoji: '💰', name: 'Money Bag', keywords: ['dollar', 'wealth', 'budget'] },
      { emoji: '💳', name: 'Credit Card', keywords: ['payment', 'visa', 'mastercard'] },
    ],
  },
  {
    id: 'symbols',
    name: 'Symbols & flags',
    emojis: [
      { emoji: '❤️', name: 'Red Heart', keywords: ['love', 'favorite', 'heart'] },
      { emoji: '🧡', name: 'Orange Heart', keywords: ['love', 'heart'] },
      { emoji: '💛', name: 'Yellow Heart', keywords: ['friendship', 'heart'] },
      { emoji: '💚', name: 'Green Heart', keywords: ['nature', 'heart'] },
      { emoji: '💙', name: 'Blue Heart', keywords: ['peace', 'heart'] },
      { emoji: '💜', name: 'Purple Heart', keywords: ['royalty', 'heart'] },
      { emoji: '🖤', name: 'Black Heart', keywords: ['dark', 'heart'] },
      { emoji: '🤍', name: 'White Heart', keywords: ['pure', 'heart'] },
      { emoji: '💔', name: 'Broken Heart', keywords: ['sad', 'breakup'] },
      { emoji: '❤️‍🔥', name: 'Heart on Fire', keywords: ['passion', 'intense'] },
      { emoji: '✨', name: 'Sparkles', keywords: ['magic', 'glitter', 'ai'] },
      { emoji: '✅', name: 'Check Mark Button', keywords: ['done', 'ok', 'correct', 'pass'] },
      { emoji: '✔️', name: 'Check Mark', keywords: ['complete', 'yes'] },
      { emoji: '❌', name: 'Cross Mark', keywords: ['no', 'wrong', 'fail', 'cancel'] },
      { emoji: '⚠️', name: 'Warning', keywords: ['alert', 'caution', 'danger'] },
      { emoji: '🚫', name: 'Prohibited', keywords: ['forbidden', 'stop'] },
      { emoji: '💯', name: 'Hundred Points', keywords: ['perfect', 'score', '100'] },
      { emoji: '🔥', name: 'Fire', keywords: ['trending', 'hot', 'lit'] },
      { emoji: '⚡', name: 'High Voltage', keywords: ['fast', 'speed', 'zap'] },
      { emoji: '🌐', name: 'Globe with Meridians', keywords: ['world', 'web', 'internet'] },
      { emoji: '🚩', name: 'Triangular Flag', keywords: ['milestone', 'mark', 'goal'] },
      { emoji: '🏁', name: 'Chequered Flag', keywords: ['finish', 'race', 'done'] },
    ],
  },
];
