import {
  Laptop,
  Code,
  Terminal,
  Cpu,
  Database,
  Server,
  HardDrive,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Bug,
  Workflow,
  Binary,
  Radio,
  Wifi,
  Globe,
  Cloud,
  FileCode,
  Folder,
  FolderGit2,
  FileText,
  Files,
  Archive,
  Package,
  Box,
  Boxes,
  Layers,
  LayoutGrid,
  Kanban,
  ListTodo,
  CheckSquare,
  Calendar,
  Clock,
  Milestone,
  Target,
  Bookmark,
  Tag,
  Flag,
  Pin,
  Zap,
  Sparkles,
  Flame,
  Rocket,
  Star,
  Heart,
  Trophy,
  Award,
  Crown,
  Lightbulb,
  Compass,
  Wrench,
  Key,
  Lock,
  Shield,
  Microscope,
  Atom,
  TestTube,
  Dna,
  BookOpen,
  GraduationCap,
  Search,
  BarChart2,
  BarChart3,
  LineChart,
  PieChart,
  TrendingUp,
  Activity,
  DollarSign,
  Coins,
  Wallet,
  CreditCard,
  Briefcase,
  Palette,
  Brush,
  Image,
  Camera,
  Film,
  Music,
  Headphones,
  Sliders,
  SlidersHorizontal,
  MessageSquare,
  MessagesSquare,
  Mail,
  Send,
  Share2,
  User,
  Users,
  Bell,
  Home,
  Settings,
  Hash,
  type LucideIcon,
} from 'lucide-react';

export interface IconItem {
  id: string;
  name: string;
  icon: LucideIcon;
  category: string;
  keywords: string[];
}

export const ICON_PALETTE = [
  { id: 'charcoal', hex: '#6b7280', label: 'Default Gray' },
  { id: 'slate', hex: '#475569', label: 'Slate' },
  { id: 'indigo', hex: '#6366f1', label: 'Indigo' },
  { id: 'sky', hex: '#0ea5e9', label: 'Blue' },
  { id: 'green', hex: '#10b981', label: 'Green' },
  { id: 'amber', hex: '#eab308', label: 'Yellow' },
  { id: 'orange', hex: '#f97316', label: 'Orange' },
  { id: 'rose', hex: '#f43f5e', label: 'Red' },
  { id: 'purple', hex: '#a855f7', label: 'Purple' },
] as const;

export const ICONS: IconItem[] = [
  // Tech & Development
  { id: 'laptop', name: 'Laptop', icon: Laptop, category: 'tech', keywords: ['computer', 'pc', 'mac', 'device'] },
  { id: 'code', name: 'Code', icon: Code, category: 'tech', keywords: ['programming', 'developer', 'html', 'syntax'] },
  { id: 'terminal', name: 'Terminal', icon: Terminal, category: 'tech', keywords: ['cli', 'bash', 'console', 'shell'] },
  { id: 'cpu', name: 'CPU', icon: Cpu, category: 'tech', keywords: ['processor', 'hardware', 'chip', 'ai'] },
  { id: 'database', name: 'Database', icon: Database, category: 'tech', keywords: ['sql', 'storage', 'data', 'postgres'] },
  { id: 'server', name: 'Server', icon: Server, category: 'tech', keywords: ['backend', 'hosting', 'cloud', 'node'] },
  { id: 'hard-drive', name: 'Hard Drive', icon: HardDrive, category: 'tech', keywords: ['disk', 'storage', 'ssd'] },
  { id: 'git-branch', name: 'Git Branch', icon: GitBranch, category: 'tech', keywords: ['git', 'version', 'branch'] },
  { id: 'git-commit', name: 'Git Commit', icon: GitCommit, category: 'tech', keywords: ['git', 'commit', 'history'] },
  { id: 'git-pull-request', name: 'Pull Request', icon: GitPullRequest, category: 'tech', keywords: ['pr', 'merge', 'git'] },
  { id: 'bug', name: 'Bug', icon: Bug, category: 'tech', keywords: ['issue', 'error', 'debug', 'problem'] },
  { id: 'workflow', name: 'Workflow', icon: Workflow, category: 'tech', keywords: ['automation', 'pipeline', 'flow'] },
  { id: 'binary', name: 'Binary', icon: Binary, category: 'tech', keywords: ['01', 'bytes', 'code', 'data'] },
  { id: 'radio', name: 'Radio', icon: Radio, category: 'tech', keywords: ['broadcast', 'signal', 'wireless'] },
  { id: 'wifi', name: 'Wi-Fi', icon: Wifi, category: 'tech', keywords: ['internet', 'network', 'connection'] },
  { id: 'globe', name: 'Globe', icon: Globe, category: 'tech', keywords: ['world', 'web', 'internet', 'public'] },
  { id: 'cloud', name: 'Cloud', icon: Cloud, category: 'tech', keywords: ['storage', 'aws', 'gcp', 'cloud'] },
  { id: 'file-code', name: 'File Code', icon: FileCode, category: 'tech', keywords: ['script', 'source', 'file'] },

  // Management & Work
  { id: 'folder', name: 'Folder', icon: Folder, category: 'work', keywords: ['directory', 'files', 'project'] },
  { id: 'folder-git', name: 'Git Folder', icon: FolderGit2, category: 'work', keywords: ['repo', 'repository'] },
  { id: 'file-text', name: 'File Text', icon: FileText, category: 'work', keywords: ['doc', 'document', 'note'] },
  { id: 'files', name: 'Files', icon: Files, category: 'work', keywords: ['documents', 'multiple'] },
  { id: 'archive', name: 'Archive', icon: Archive, category: 'work', keywords: ['box', 'storage', 'history'] },
  { id: 'package', name: 'Package', icon: Package, category: 'work', keywords: ['box', 'npm', 'module', 'delivery'] },
  { id: 'box', name: 'Box', icon: Box, category: 'work', keywords: ['container', 'item'] },
  { id: 'boxes', name: 'Boxes', icon: Boxes, category: 'work', keywords: ['inventory', 'containers'] },
  { id: 'layers', name: 'Layers', icon: Layers, category: 'work', keywords: ['stack', 'tier', 'levels'] },
  { id: 'grid', name: 'Grid', icon: LayoutGrid, category: 'work', keywords: ['dashboard', 'layout', 'tiles'] },
  { id: 'kanban', name: 'Kanban', icon: Kanban, category: 'work', keywords: ['board', 'columns', 'scrum'] },
  { id: 'tasks', name: 'Tasks', icon: ListTodo, category: 'work', keywords: ['todo', 'checklist', 'work items'] },
  { id: 'check-square', name: 'Check Square', icon: CheckSquare, category: 'work', keywords: ['done', 'verify'] },
  { id: 'calendar', name: 'Calendar', icon: Calendar, category: 'work', keywords: ['date', 'schedule', 'events'] },
  { id: 'clock', name: 'Clock', icon: Clock, category: 'work', keywords: ['time', 'history', 'deadline'] },
  { id: 'milestone', name: 'Milestone', icon: Milestone, category: 'work', keywords: ['goal', 'roadmap', 'sign'] },
  { id: 'target', name: 'Target', icon: Target, category: 'work', keywords: ['objective', 'goal', 'okr'] },
  { id: 'bookmark', name: 'Bookmark', icon: Bookmark, category: 'work', keywords: ['favorite', 'save', 'mark'] },
  { id: 'tag', name: 'Tag', icon: Tag, category: 'work', keywords: ['label', 'category', 'badge'] },
  { id: 'flag', name: 'Flag', icon: Flag, category: 'work', keywords: ['priority', 'mark', 'goal'] },
  { id: 'pin', name: 'Pin', icon: Pin, category: 'work', keywords: ['stick', 'highlight', 'attach'] },

  // Productivity & Innovation
  { id: 'zap', name: 'Zap', icon: Zap, category: 'productivity', keywords: ['fast', 'speed', 'energy', 'lightning'] },
  { id: 'sparkles', name: 'Sparkles', icon: Sparkles, category: 'productivity', keywords: ['ai', 'magic', 'clean', 'new'] },
  { id: 'flame', name: 'Flame', icon: Flame, category: 'productivity', keywords: ['hot', 'streak', 'fire', 'trending'] },
  { id: 'rocket', name: 'Rocket', icon: Rocket, category: 'productivity', keywords: ['launch', 'deploy', 'fast', 'startup'] },
  { id: 'star', name: 'Star', icon: Star, category: 'productivity', keywords: ['favorite', 'rating', 'important'] },
  { id: 'heart', name: 'Heart', icon: Heart, category: 'productivity', keywords: ['love', 'like', 'health'] },
  { id: 'trophy', name: 'Trophy', icon: Trophy, category: 'productivity', keywords: ['winner', 'achievement', 'prize'] },
  { id: 'award', name: 'Award', icon: Award, category: 'productivity', keywords: ['badge', 'medal', 'honor'] },
  { id: 'crown', name: 'Crown', icon: Crown, category: 'productivity', keywords: ['king', 'premium', 'vip', 'leader'] },
  { id: 'lightbulb', name: 'Lightbulb', icon: Lightbulb, category: 'productivity', keywords: ['idea', 'creative', 'solution'] },
  { id: 'compass', name: 'Compass', icon: Compass, category: 'productivity', keywords: ['direction', 'explore', 'navigation'] },
  { id: 'wrench', name: 'Wrench', icon: Wrench, category: 'productivity', keywords: ['tool', 'fix', 'maintain'] },
  { id: 'key', name: 'Key', icon: Key, category: 'productivity', keywords: ['secret', 'security', 'unlock'] },
  { id: 'lock', name: 'Lock', icon: Lock, category: 'productivity', keywords: ['private', 'secure', 'protect'] },
  { id: 'shield', name: 'Shield', icon: Shield, category: 'productivity', keywords: ['security', 'safe', 'guard'] },

  // Science & Research
  { id: 'microscope', name: 'Microscope', icon: Microscope, category: 'research', keywords: ['science', 'lab', 'biology', 'inspect'] },
  { id: 'atom', name: 'Atom', icon: Atom, category: 'research', keywords: ['physics', 'science', 'react', 'core'] },
  { id: 'test-tube', name: 'Test Tube', icon: TestTube, category: 'research', keywords: ['chemistry', 'experiment', 'lab'] },
  { id: 'dna', name: 'DNA', icon: Dna, category: 'research', keywords: ['genetics', 'life', 'science'] },
  { id: 'book-open', name: 'Book Open', icon: BookOpen, category: 'research', keywords: ['read', 'paper', 'literature', 'study'] },
  { id: 'graduation-cap', name: 'Academic Cap', icon: GraduationCap, category: 'research', keywords: ['education', 'university', 'phd'] },
  { id: 'search', name: 'Search', icon: Search, category: 'research', keywords: ['find', 'discover', 'lookup', 'query'] },

  // Finance & Analytics
  { id: 'bar-chart', name: 'Bar Chart', icon: BarChart2, category: 'finance', keywords: ['metrics', 'graph', 'analytics'] },
  { id: 'bar-chart-3', name: 'Columns', icon: BarChart3, category: 'finance', keywords: ['chart', 'stats'] },
  { id: 'line-chart', name: 'Line Chart', icon: LineChart, category: 'finance', keywords: ['trend', 'growth', 'graph'] },
  { id: 'pie-chart', name: 'Pie Chart', icon: PieChart, category: 'finance', keywords: ['share', 'ratio', 'analytics'] },
  { id: 'trending-up', name: 'Trending Up', icon: TrendingUp, category: 'finance', keywords: ['growth', 'increase', 'profit'] },
  { id: 'activity', name: 'Activity', icon: Activity, category: 'finance', keywords: ['pulse', 'health', 'heartbeat', 'monitor'] },
  { id: 'dollar-sign', name: 'Dollar', icon: DollarSign, category: 'finance', keywords: ['money', 'revenue', 'currency', 'price'] },
  { id: 'coins', name: 'Coins', icon: Coins, category: 'finance', keywords: ['crypto', 'tokens', 'cash'] },
  { id: 'wallet', name: 'Wallet', icon: Wallet, category: 'finance', keywords: ['funds', 'payment', 'finance'] },
  { id: 'credit-card', name: 'Credit Card', icon: CreditCard, category: 'finance', keywords: ['payment', 'billing', 'subscription'] },
  { id: 'briefcase', name: 'Briefcase', icon: Briefcase, category: 'finance', keywords: ['business', 'work', 'job'] },

  // Media & Creative
  { id: 'palette', name: 'Palette', icon: Palette, category: 'creative', keywords: ['colors', 'art', 'theme', 'ui'] },
  { id: 'brush', name: 'Brush', icon: Brush, category: 'creative', keywords: ['paint', 'draw', 'design'] },
  { id: 'image', name: 'Image', icon: Image, category: 'creative', keywords: ['photo', 'picture', 'graphic'] },
  { id: 'camera', name: 'Camera', icon: Camera, category: 'creative', keywords: ['photo', 'video', 'lens'] },
  { id: 'film', name: 'Film', icon: Film, category: 'creative', keywords: ['video', 'movie', 'recording'] },
  { id: 'music', name: 'Music', icon: Music, category: 'creative', keywords: ['sound', 'audio', 'song'] },
  { id: 'headphones', name: 'Headphones', icon: Headphones, category: 'creative', keywords: ['listen', 'audio'] },
  { id: 'sliders', name: 'Sliders', icon: Sliders, category: 'creative', keywords: ['tune', 'adjust', 'mix'] },
  { id: 'sliders-h', name: 'Filters', icon: SlidersHorizontal, category: 'creative', keywords: ['controls', 'parameters'] },

  // Communication & Team
  { id: 'message', name: 'Message', icon: MessageSquare, category: 'team', keywords: ['chat', 'comment', 'talk'] },
  { id: 'messages', name: 'Messages', icon: MessagesSquare, category: 'team', keywords: ['discussion', 'forum', 'team'] },
  { id: 'mail', name: 'Mail', icon: Mail, category: 'team', keywords: ['email', 'inbox', 'letter'] },
  { id: 'send', name: 'Send', icon: Send, category: 'team', keywords: ['dispatch', 'submit', 'message'] },
  { id: 'share', name: 'Share', icon: Share2, category: 'team', keywords: ['publish', 'forward', 'collaborate'] },
  { id: 'user', name: 'User', icon: User, category: 'team', keywords: ['person', 'account', 'profile'] },
  { id: 'users', name: 'Users', icon: Users, category: 'team', keywords: ['team', 'group', 'members', 'workspace'] },
  { id: 'bell', name: 'Bell', icon: Bell, category: 'team', keywords: ['notification', 'alert', 'remind'] },
  { id: 'home', name: 'Home', icon: Home, category: 'common', keywords: ['dashboard', 'root', 'main'] },
  { id: 'settings', name: 'Settings', icon: Settings, category: 'common', keywords: ['gear', 'configure', 'admin'] },
  { id: 'hash', name: 'Hash', icon: Hash, category: 'common', keywords: ['tag', 'number', 'channel'] },
];

export const ICON_MAP: Record<string, LucideIcon> = ICONS.reduce((acc, item) => {
  acc[item.id] = item.icon;
  return acc;
}, {} as Record<string, LucideIcon>);
